# Generated by Django 2.0.4 on 2018-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
